### ISSUE TITLE
Crash: No static method addFirst(Ljava/util/List;Ljava/lang/Object;)V

### ISSUE THREAD

**Issue by arnassavickis** [exponea/exponea-android-sdk#80]
After updating from 3.14.0 to 4.1.0 we are getting crash during initialization:

```
Exception java.lang.NoSuchMethodError: No static method addFirst(Ljava/util/List;Ljava/lang/Object;)V in class Lj$/util/List$-EL; or its super classes (declaration of 'j$.util.List$-EL' appears in /data/app/~~PH1VL7jbc_LmfGoUcex7Lg==/<app package>-fj8eosIKkC9UHAmBiYhV8A==/base.apk!classes2.dex)
  at com.exponea.sdk.telemetry.CrashManager.saveLogMessage (CrashManager.kt:67)
  at com.exponea.sdk.telemetry.TelemetryManager.reportLog (TelemetryManager.kt:78)
  at com.exponea.sdk.telemetry.TelemetryManager.reportLog$default (TelemetryManager.kt:77)
  at com.exponea.sdk.util.Logger.v (Logger.kt:60)
  at com.exponea.sdk.services.ExponeaInitManager.notifyInitializedState (ExponeaInitManager.kt:20)
  at com.exponea.sdk.Exponea.init (Exponea.kt:441)
  at <app package>.initializeExponea (Application.kt:68)
  at <app package>.onCreate (Application.kt:35)
  at android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1316)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:6998)
  at android.app.ActivityThread.-$$Nest$mhandleBindApplication (Unknown Source)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:2236)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loopOnce (Looper.java:205)
  at android.os.Looper.loop (Looper.java:294)
  at android.app.ActivityThread.main (ActivityThread.java:8177)
  at java.lang.reflect.Method.invoke
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:552)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:971)
```

**Comment by adam1929** [comment]
Hi @arnassavickis thank you for reporting.
From exception message, I assume you are using dexguard/proguard and you code is obfuscated. And it seems as core as `java.util.LinkedList` is obfuscated too - as  `j$/util/List$-EL`
Try to skip obfuscation for java.util.
Or check please your kotlin, AGP and java version in your app setup against our example app https://github.com/exponea/exponea-android-sdk/blob/main/app/build.gradle
as these versions has changed due to higher Android API support.
Because method `addFirst` is legitimate method of `java.util.LinkedList` and is not static at all :-O

Please try these hints. If they would not help, please contact us with new findings. Thank you

**Comment by arnassavickis** [comment]
@adam1929 skipping obfuscation does not help.
Please check https://developer.android.com/about/versions/15/behavior-changes-15#openjdk-api-changes

**Comment by adam1929** [comment]
Thanks @arnassavickis thanks for quick answer.
I'm re-opening the issue for you.
Could you please share with us your Java, Kotlin, AGP versions, anything you think could relate? Thanks.
I tried our Example app on Android 15 (Api 15) but I was not able to simulate crash. That part of code is working normally.
Thank you

**Comment by arnassavickis** [comment]
Thank you.

Gradle JDK: jbr-17 17.0.11
Kotlin: 2.1.10
AGP: 8.8.2
compileSdk: 35
minSdk: 21
targetSdk: 35

I tried to reproduce the issue directly on your Example app, however with all the different variations - I could not reproduce it.
I ended up with assembling your SDK with updated dependencies to match my project and this change in CrashManager:
```
    @Synchronized fun saveLogMessage(parent: Any, message: String, timestamp: Long) {
        latestLogMessages.add(0, "${Date(timestamp)} ${parent.javaClass.simpleName}: $message")
        if (latestLogMessages.size > MAX_LOG_MESSAGES) {
            latestLogMessages.removeAt(latestLogMessages.size - 1)
        }
    }
```
Retested my app, everything seems to work as expected, including everything related to Exponea.
If i will have more time, I will try to reproduce the issue on your Example app and update if anything.

**Comment by adam1929** [comment]
Thanks. Your change is reasonable. I bet that crash is cause by kotlin2, as Example app is still using kotlin 1.9.
Let us investigate it more deeply. We have to keep version lowest as possible.
Thanks for patience and stay tuned!

**Comment by arnassavickis** [comment]
I was thinking about that also, or JDK, or AGP versions. However even with mimicking my projects settings/versions (everything, Kotlin version including) - I couldnt reproduce the issue on Example app. Maybe other dependencies used in my project (there are quite some of them) cause some kind of configuration issues. Cannot find any link for now.

**Comment by adam1929** [comment]
Hi @arnassavickis I tried to use your env versions and I also tried to change everything that could possible affect that method, but everything is working.
According to your findings and my findings of https://developer.android.com/sdk/api_diff/35/changes ; we decide to replace `addFirst` and `removeLast` method with non-removed API.
It will be delivered in next SDK release.
If you'll be successful in another findings, please feel free to reopen this issue.
Also if it is possible, please share your dependency tree with us, via CMS/Support. We would be able to see some culprits there maybe.
Thank you

**Comment by xcibik00** [comment]
Hi @arnassavickis , please try newest Android mSDK v4.2.0 - it should be fixed there

**Comment by adam1929** [comment]
Hi @arnassavickis did that release helped you?
Could you please share a device info or emulator info on which the issue occured? Thank you
